export enum ErrorCodes {
  INVALID_URL = 'ERR_INVALID_URL',
  SCRAPING_FAILED = 'ERR_SCRAPING_FAILED',
  NOT_SHOPIFY_STORE = 'ERR_NOT_SHOPIFY_STORE',
  AI_PROCESSING_ERROR = 'ERR_AI_PROCESSING_ERROR',
  AI_VALIDATION_FAILED = 'ERR_AI_VALIDATION_FAILED',
  RATE_LIMIT_EXCEEDED = 'ERR_RATE_LIMIT_EXCEEDED',
  INTERNAL_SERVER_ERROR = 'ERR_INTERNAL_SERVER_ERROR',
  NOT_FOUND = 'ERR_NOT_FOUND',
  VALIDATION_ERROR = 'ERR_VALIDATION_ERROR',
  UNAUTHORIZED = 'ERR_UNAUTHORIZED',
}
